# https://rubocop.readthedocs.io/en/latest/cops_layout/
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundModuleBody:
  Enabled: false
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Layout/MultilineMethodCallBrace:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Lint/BooleanSymbol:
  Enabled: false

# https://rubocop.readthedocs.io/en/latest/cops_metrics/
Metrics/LineLength:
  Max: 100

Naming/HeredocDelimiterNaming:
  Enable: false

# https://rubocop.readthedocs.io/en/latest/cops_style/
Style/Alias:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Encoding:
  Enabled: false
Sylte/IfUnlessModifier:
  Enabled: false
